/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/parameters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ReferenceController_parameters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ReferenceController_stations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/measurements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MeasurementsController_listAll"];
        put?: never;
        post: operations["MeasurementsController_submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/measurements/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["MeasurementsController_submitBatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/measurements/station": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MeasurementsController_listForStation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/measurements/returned": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MeasurementsController_listReturned"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/measurements/{id}/recheck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["MeasurementsController_recheck"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/anomalies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AnomaliesController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/anomalies/{id}/return": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AnomaliesController_returnToStation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/anomalies/{id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AnomaliesController_accept"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/anomalies/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AnomaliesController_reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instruments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["InstrumentsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instruments/{id}/failure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["InstrumentsController_reportFailure"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/failures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["InstrumentsController_listFailures"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/anomalies-delays": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ReportsController_anomaliesAndDelays"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/anomalies-delays/csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ReportsController_anomaliesAndDelaysCsv"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginDto: {
            /** @example observer1 */
            login: string;
            /** @example observer123 */
            password: string;
        };
        TokensDto: {
            accessToken: string;
            refreshToken: string;
        };
        RefreshDto: {
            refreshToken: string;
        };
        /** @enum {string} */
        Role: "OBSERVER" | "MANAGER";
        MeStationDto: {
            id: number;
            code: string;
            name: string;
        };
        MeDto: {
            id: number;
            login: string;
            fullName: string;
            role: components["schemas"]["Role"];
            station: components["schemas"]["MeStationDto"] | null;
        };
        ParameterDto: {
            id: number;
            code: string;
            name: string;
            unit: string;
            minValue: number;
            maxValue: number;
            precision: number;
            neighborTolerance: number;
        };
        /** @enum {string} */
        StationType: "GROUND" | "AEROLOGICAL" | "MARINE" | "AUTOMATIC";
        StationDto: {
            id: number;
            code: string;
            name: string;
            type: components["schemas"]["StationType"];
            latitude: number;
            longitude: number;
            district: string;
        };
        CreateMeasurementDto: {
            parameterId: number;
            instrumentId: number;
            /** @description Срок наблюдения, ISO 8601 */
            observedAt: string;
            value: number;
        };
        RefStationDto: {
            id: number;
            code: string;
            name: string;
        };
        RefParameterDto: {
            id: number;
            code: string;
            name: string;
            unit: string;
            precision: number;
        };
        RefInstrumentDto: {
            id: number;
            name: string;
        };
        /** @enum {string} */
        MeasurementStatus: "DRAFT" | "RECEIVED" | "FLAGGED" | "RETURNED" | "RECHECKED" | "ACCEPTED" | "REJECTED";
        /** @enum {string} */
        CheckType: "RANGE" | "NEIGHBORS" | "OUTLIER";
        /** @enum {string} */
        Verdict: "NORMAL" | "SUSPECT";
        CheckResultDto: {
            id: number;
            revision: number;
            type: components["schemas"]["CheckType"];
            verdict: components["schemas"]["Verdict"];
            deviation: number | null;
            referenceValue: number | null;
            note: string;
            /** Format: date-time */
            createdAt: string;
        };
        RevisionDto: {
            revision: number;
            value: number;
            reason: string | null;
            author: string;
            /** Format: date-time */
            createdAt: string;
        };
        HistoryEntryDto: {
            fromState: string | null;
            toState: string;
            comment: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        MeasurementDto: {
            id: number;
            station: components["schemas"]["RefStationDto"];
            parameter: components["schemas"]["RefParameterDto"];
            instrument: components["schemas"]["RefInstrumentDto"];
            /** Format: date-time */
            observedAt: string;
            /** Format: date-time */
            receivedAt: string;
            delayed: boolean;
            status: components["schemas"]["MeasurementStatus"];
            value: number;
            currentRevision: number;
            /** @description Проверки текущей ревизии */
            checks: components["schemas"]["CheckResultDto"][];
            revisions: components["schemas"]["RevisionDto"][];
            history: components["schemas"]["HistoryEntryDto"][];
        };
        BatchItemDto: {
            parameterId: number;
            instrumentId: number;
            /** @description Срок наблюдения, ISO 8601 */
            observedAt: string;
            value: number;
            /** @description Локальный id записи в очереди клиента */
            clientId: string;
        };
        BatchDto: {
            items: components["schemas"]["BatchItemDto"][];
        };
        BatchResultItemDto: {
            clientId: string;
            /** @enum {string} */
            status: "created" | "duplicate" | "error";
            measurementId?: number;
            error?: string;
        };
        BatchResultDto: {
            items: components["schemas"]["BatchResultItemDto"][];
        };
        RecheckDto: {
            value: number;
            reason: string;
        };
        CommentDto: {
            comment: string;
        };
        /** @enum {string} */
        InstrumentRole: "PRIMARY" | "RESERVE";
        /** @enum {string} */
        InstrumentState: "IN_SERVICE" | "BROKEN" | "VERIFICATION" | "DECOMMISSIONED";
        /** @enum {string} */
        VerificationStatus: "OK" | "DUE_SOON" | "OVERDUE";
        InstrumentDto: {
            id: number;
            name: string;
            model: string;
            station: components["schemas"]["RefStationDto"];
            role: components["schemas"]["InstrumentRole"];
            state: components["schemas"]["InstrumentState"];
            /** Format: date-time */
            commissionedAt: string;
            /** Format: date-time */
            nextVerificationAt: string;
            verificationStatus: components["schemas"]["VerificationStatus"];
            parameters: components["schemas"]["RefParameterDto"][];
        };
        ReportFailureDto: {
            description: string;
            /** @description Резервный прибор, который берёт на себя функции */
            reserveInstrumentId?: number;
        };
        FailureInstrumentDto: {
            id: number;
            name: string;
            model: string;
        };
        FailureDto: {
            id: number;
            instrument: components["schemas"]["FailureInstrumentDto"];
            reserveInstrument: components["schemas"]["FailureInstrumentDto"] | null;
            station: components["schemas"]["RefStationDto"];
            reportedBy: string;
            description: string;
            /** Format: date-time */
            openedAt: string;
            /** Format: date-time */
            closedAt: string | null;
        };
        ReportStationRowDto: {
            total: number;
            flagged: number;
            flaggedRange: number;
            flaggedNeighbors: number;
            flaggedOutlier: number;
            confirmedAfterRecheck: number;
            correctedAfterRecheck: number;
            rejected: number;
            falsePositiveShare: number | null;
            delayedCount: number;
            delayTotalMin: number;
            delayAvgMin: number | null;
            maxOutageMin: number;
            stationId: number;
            stationCode: string;
            stationName: string;
        };
        ReportTotalsDto: {
            total: number;
            flagged: number;
            flaggedRange: number;
            flaggedNeighbors: number;
            flaggedOutlier: number;
            confirmedAfterRecheck: number;
            correctedAfterRecheck: number;
            rejected: number;
            falsePositiveShare: number | null;
            delayedCount: number;
            delayTotalMin: number;
            delayAvgMin: number | null;
            maxOutageMin: number;
        };
        ReportDailyRowDto: {
            date: string;
            flagged: number;
            delayed: number;
        };
        ReportTopStationDto: {
            stationCode: string;
            stationName: string;
            flagged: number;
        };
        AnomalyDelayReportDto: {
            /** Format: date-time */
            from: string;
            /** Format: date-time */
            to: string;
            stations: components["schemas"]["ReportStationRowDto"][];
            totals: components["schemas"]["ReportTotalsDto"];
            daily: components["schemas"]["ReportDailyRowDto"][];
            topStation: components["schemas"]["ReportTopStationDto"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokensDto"];
                };
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokensDto"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeDto"];
                };
            };
        };
    };
    ReferenceController_parameters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParameterDto"][];
                };
            };
        };
    };
    ReferenceController_stations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StationDto"][];
                };
            };
        };
    };
    MeasurementsController_listAll: {
        parameters: {
            query?: {
                status?: components["schemas"]["MeasurementStatus"];
                stationId?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeasurementDto"][];
                };
            };
        };
    };
    MeasurementsController_submit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMeasurementDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeasurementDto"];
                };
            };
        };
    };
    MeasurementsController_submitBatch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchResultDto"];
                };
            };
        };
    };
    MeasurementsController_listForStation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeasurementDto"][];
                };
            };
        };
    };
    MeasurementsController_listReturned: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeasurementDto"][];
                };
            };
        };
    };
    MeasurementsController_recheck: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecheckDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeasurementDto"];
                };
            };
        };
    };
    AnomaliesController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeasurementDto"][];
                };
            };
        };
    };
    AnomaliesController_returnToStation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeasurementDto"];
                };
            };
        };
    };
    AnomaliesController_accept: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeasurementDto"];
                };
            };
        };
    };
    AnomaliesController_reject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeasurementDto"];
                };
            };
        };
    };
    InstrumentsController_list: {
        parameters: {
            query?: {
                stationId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentDto"][];
                };
            };
        };
    };
    InstrumentsController_reportFailure: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportFailureDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FailureDto"];
                };
            };
        };
    };
    InstrumentsController_listFailures: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FailureDto"][];
                };
            };
        };
    };
    ReportsController_anomaliesAndDelays: {
        parameters: {
            query?: {
                /** @description Начало периода (ISO), по умолчанию −30 дней */
                from?: string;
                /** @description Конец периода (ISO), по умолчанию сейчас */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnomalyDelayReportDto"];
                };
            };
        };
    };
    ReportsController_anomaliesAndDelaysCsv: {
        parameters: {
            query?: {
                /** @description Начало периода (ISO), по умолчанию −30 дней */
                from?: string;
                /** @description Конец периода (ISO), по умолчанию сейчас */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
